// USER
export const USER_CHANGE_FORM = "USER_CHANGE_FORM";
export const USER_SET_AUTH = "USER_SET_AUTH";
export const USER_SENDING_REQUEST = "USER_SENDING_REQUEST";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REQUEST_ERROR = "USER_REQUEST_ERROR";
export const USER_CLEAR_ERROR = "USER_CLEAR_ERROR";
